comment: ''
log_folder: ~/logs/AdversarialTraining
partition: long
# nodes: 1
# gpus_per_node: 1
cpus_per_task: 8
slurm_gres: 'gpu:rtx8000:1'
time_in_min: 5760  # 4 days
mem_by_gpu: 24
slurm_array_parallelism: 8
