comment: ''
log_folder: ~/logs/AdversarialTraining
partition: unkillable
# nodes: 1
slurm_gres: 'gpu:rtx8000:1'
# gpus_per_node: 1
cpus_per_task: 8
time_in_min: 2880
mem_by_gpu: 6
slurm_array_parallelism: 1